# Generated by Django 5.1.4 on 2025-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
