# Generated by Django 5.1.4 on 2025-06-21 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customers_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonepayPurchase',
            fields=[
                ('merchant_order_id', models.CharField(max_length=63, primary_key=True, serialize=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('phonepe_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=100, unique=True)),
                ('sale_timestamp', models.DateTimeField()),
                ('order_number', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('product_permalink', models.CharField(max_length=255)),
                ('short_product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_cents', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('ip_country', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('custom_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='users.customers')),
            ],
        ),
    ]
