# Generated by Django 5.1.4 on 2025-06-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_phonepaypurchase_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonepaypurchase',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phonepaypurchase',
            name='raw_response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonepaypurchase',
            name='webhook_event',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
