# Generated by Django 5.1.4 on 2025-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_phonepaypurchase_phonepe_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonepaypurchase',
            name='merchant_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phonepaypurchase',
            name='phonepe_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phonepaypurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('REFUND_FAILED', 'Refund Failed')], default='PENDING', max_length=20),
        ),
    ]
