# Generated by Django 5.1.4 on 2025-06-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_phonepaypurchase_merchant_refund_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonepaypurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUNDED', 'Refunded'), ('REFUND_CONFIRMED', 'Refund confirmed'), ('REFUND_FAILED', 'Refund Failed')], default='PENDING', max_length=20),
        ),
    ]
